### ISSUE TITLE
complaining about if typescript is worst or not

### ISSUE THREAD

**Issue by kot83** [auguwu/Noel#1]

**Comment by voiduwu** [comment]
kot

**Comment by voiduwu** [comment]
u qt

**Comment by ohlookitsderpy** [comment]
kot has a point

**Comment by Yara-Illig** [comment]
ur all qts

**Comment by ohlookitsderpy** [comment]
no u

**Comment by auguwu** [comment]
ur all megu qts ok thank plus misaki is broken and jda succ (~~even tho it has 30+ days :^)~~)

**Comment by auguwu** [comment]
typescript is fun !!!!

**Comment by ohlookitsderpy** [comment]
typescript is ass

**Comment by auguwu** [comment]
Kot ur qt
but
you
hate
node.js?

**Comment by kot83** [comment]
typescript is better than nodejs but its still trash
its just that nodejs is even more trash

**Comment by voiduwu** [comment]
bear

**Comment by ohlookitsderpy** [comment]
do i see a python/java fanboy who uses jetbrains here

**Comment by ohlookitsderpy** [comment]
jetbrains huge succ on the cpu

**Comment by ohlookitsderpy** [comment]
import and public void big dumb

**Comment by voiduwu** [comment]
what

**Comment by auguwu** [comment]
@voiduwu qtaf :heart:

**Comment by auguwu** [comment]
derpy hating on jetbrains and jvm 😡

**Comment by ohlookitsderpy** [comment]
jvm eats ram and cpu and is old

**Comment by ohlookitsderpy** [comment]
jetbrains ugly complicated and overpriced

**Comment by kot83** [comment]
ikr

**Comment by kot83** [comment]
just use .NET like a sane person :^)

**Comment by kot83** [comment]
java RUNS ON A VIRTUAL MACHINE

**Comment by kot83** [comment]
you can compile it to machine code, sure, but who ever does that :eyes:

**Comment by kot83** [comment]
@auguwu jvm bad, jetbrains bad, hahayes

**Comment by kot83** [comment]
R# and Rider bad too
IntelliJ is ok but its made for java so bad

**Comment by Yara-Illig** [comment]
yes kot and ur all qt's

**Comment by auguwu** [comment]
why not make discord.txt :^)

**Comment by kot83** [comment]
no ty

**Comment by auguwu** [comment]
I'm keeping this repository until I'm done with AugustBoat...

**Comment by kot83** [comment]
please delete this

**Comment by CFTheMaster** [comment]
...

**Comment by kot83** [comment]
wtf is this thread tho lmao

**Comment by auguwu** [comment]
A meme thread until auguboat is done imo
